### ISSUE TITLE
Installation incomplete - MD simulation aborts with error message "/bin/sh: 1: srun: not found"

### ISSUE THREAD

**Issue by Doro35** [Liu-group/AutoSolvate#2]
Could you please explain me how to work around it? This happens both with conda installs and manual installs

**Comment by euhruska** [comment]
In command line set --srunuse False or in GUI set "Use srun to execute command?" to No. You can try dryrun and check the files runMM.sh and runQMMM.sh if they look correct.

**Comment by Doro35** [comment]
it worked! thank you 💯 for some reason -r "False" didn't work but skipping the -r and writting --srunuse False worked!
