### ISSUE TITLE
Error opening unit   30: File "qmmm.ncrst" is missing or unreadable

### ISSUE THREAD

**Issue by Doro35** [Liu-group/AutoSolvate#3]
qmmm.ncrst was missing; how can I ensure that it is written?

**Comment by euhruska** [comment]
Do you use TeraChem or Gaussian? For autosolvate boxgen both TeraChem and Gaussian are supported, but autosolvate mdrun supports currently only Terachem.

**Comment by euhruska** [comment]
Adjusted Documentation to clarify.
