### ISSUE TITLE
Trouble running anions

### ISSUE THREAD

**Issue by Ryanjoha9** [Liu-group/AutoSolvate#5]
Hello! I'm having issues running anions, both from the gui and from the command line.

I'm currently running anionic HBDI, and I keep getting the following output when I try to run it.

I'm rather new to the code and would appreciate any assistance with this! I've included an image of the molecule for reference
![HBDI_anion](https://user-images.githubusercontent.com/113057201/188953799-37700125-5fed-4211-9bcc-05b1cc2d5ec8.png)

AutoSolvate is starting in command line mode!
Running the module to generate solvent box and force field parameters.
Main/solutexyz HBDI_anion.xyz
Charge: -1
Output: HBDI_anion_ws
WARNING: Amber home directory is not specified in input options
WARNING: Checking AMBERHOME environment variable...
['echo', '$AMBERHOME']
WARNING: AMBERHOME detected:  $AMBERHOME

Converting xyz to pdb
Generate frcmod file for the solute
cleaning up solute.xyz.pdb
Then write out mol2

Welcome to antechamber 22.0: molecular input file processor.

Info: acdoctor mode is on: check and diagnose problems in the input file.
Info: The atom type is set to gaff; the options available to the -at flag are
      gaff, gaff2, amber, bcc, and sybyl.

-- Check Format for pdb File --
   Status: pass
-- Check Unusual Elements --
   Status: pass
![HBDI_anion](https://user-images.githubusercontent.com/113057201/188953727-827edf53-d1bc-48ee-82b3-5e59f24c8186.png)

-- Check Open Valences --
   Status: pass
-- Check Geometry --
      for those bonded   
      for those not bonded   
   Status: pass
-- Check Weird Bonds --
   Status: pass
-- Check Number of Units --
   Status: pass
acdoctor mode has completed checking the input file.

Info: Bond types are assigned for valence state (1) with penalty (1).
Info: Total number of electrons: 113; net charge: 0
Info: The number of electrons is odd (113).
      Please check the total charge (-nc flag) and spin multiplicity (-m flag).

Running: /Users/rdjohann/opt/anaconda3/envs/autosolvate/bin/sqm -O -i sqm.in -o sqm.out
/Users/rdjohann/opt/anaconda3/envs/autosolvate/bin/wrapped_progs/antechamber: Fatal Error!
Cannot properly run "/Users/rdjohann/opt/anaconda3/envs/autosolvate/bin/sqm -O -i sqm.in -o sqm.out".
Finally generate frcmod with parmchk2
Cannot open file (solute.mol2) with mode (r).
No such file or directory
Now create the solute library file
Traceback (most recent call last):
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/bin/autosolvate", line 33, in <module>
    sys.exit(load_entry_point('autosolvate==0.1.3+3.gc4e0fcb', 'console_scripts', 'autosolvate')())
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/lib/python3.8/site-packages/autosolvate-0.1.3+3.gc4e0fcb-py3.8.egg/autosolvate/__main__.py", line 38, in main
    startboxgen(args[1:])
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/lib/python3.8/site-packages/autosolvate-0.1.3+3.gc4e0fcb-py3.8.egg/autosolvate/autosolvate.py", line 734, in startboxgen
    builder.build()
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/lib/python3.8/site-packages/autosolvate-0.1.3+3.gc4e0fcb-py3.8.egg/autosolvate/autosolvate.py", line 596, in build
    self.createLib()
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/lib/python3.8/site-packages/autosolvate-0.1.3+3.gc4e0fcb-py3.8.egg/autosolvate/autosolvate.py", line 320, in createLib
    self.writeTleapcmd1()
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/lib/python3.8/site-packages/autosolvate-0.1.3+3.gc4e0fcb-py3.8.egg/autosolvate/autosolvate.py", line 293, in writeTleapcmd1
    self.getHeadTail()
  File "/Users/rdjohann/opt/anaconda3/envs/autosolvate/lib/python3.8/site-packages/autosolvate-0.1.3+3.gc4e0fcb-py3.8.egg/autosolvate/autosolvate.py", line 262, in getHeadTail
    pdb = open('solute.mol2').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'solute.mol2'

**Comment by euhruska** [comment]
Can you try adding `-u 2` to the `autosolvate boxgen` command? (spinmultiplicity 2).

**Comment by Ryanjoha9** [comment]
I'm also having trouble getting the program to access gaussian on my computer, it's located in /Applications/g16 (on mac), but it seems to want to go through /opt/packages/gaussian/g16RevC.01/g16/, which doesn't exist. (I'm working in a conda environment). I used the -d flag to direct it to the proper directory, but I get the following error:

Then run Gaussian...
export GAUSS_EXEDIR=/opt/packages/gaussian/g16RevC.01/g16/; export GAUSS_SCRDIR=/Users/rdjohann/Autosolvate_input/HBDI_anion/tmp_gaussian; /Applications/g16 < gcrt.com > gcrt.out
/bin/sh: /Applications/g16: is a directory
gaussian failed to generate solute.gesp


Although my molecule is closed shell (with the negative charge on the oxygen), would this have any effect on the calculation? Or is it just to get the box generated?

**Comment by euhruska** [comment]
Can you specify the whole `autosolvate boxgen` command you use?

**Comment by Ryanjoha9** [comment]
autosolvate boxgen -m HBDI_anion.xyz -c -1 -u 2 -g "resp" -d /Applications/g16 -o HBDI_anion_ws

**Comment by euhruska** [comment]
Is `/Applications/g16/ ` the absolute path? The absolute path is required.
There is currently a typo in `-d` , until this bug is fixed please use: 
`autosolvate boxgen -m HBDI_anion.xyz -c -1 -u 2 -g "resp" -e /Applications/g16/ -o HBDI_anion_ws`

**Comment by Ryanjoha9** [comment]
I think that fixed part of the problem.. I'm still getting the error:

Then run Gaussian...
export GAUSS_EXEDIR=/Applications/g16/; export GAUSS_SCRDIR=/Users/rdjohann/Autosolvate_input/HBDI_anion/tmp_gaussian; g16 < gcrt.com > gcrt.out
gaussian failed to generate solute.gesp

Do you know if this is a problem with gaussian, or something else?

Thanks for your help!

**Comment by euhruska** [comment]
The file gcrt.out should provide clues why gaussian failed.

**Comment by Ryanjoha9** [comment]
Says spinmultiplicty 2 is impossible with 114 electrons, changed to -u 1, still using resp and it worked fine (although it took quite a while).

Seems like there might be some miscommunication between acdoctor and antechamber (maybe? or another program) when using bcc, since it originally identified the molecule as having 113 electrons, but it actually had 114.
